### GET all students
GET http://127.0.0.1:5001/students
Content-Type: application/json

###

### GET one student by ID
GET http://127.0.0.1:5001/students/1
Content-Type: application/json

###

### POST create a new student
POST http://127.0.0.1:5001/students
Content-Type: application/json

{
    "name": "Nouhaila",
    "email": "nouhaila@example.com",
    "age": 25,
    "gender": "female"
}

###

### PUT update a student
PUT http://127.0.0.1:5001/students/1
Content-Type: application/json

{
    "name": "John Doe Updated",
    "email": "new.email@example.com"
}

###

### DELETE a student
DELETE http://127.0.0.1:5001/students/1
Content-Type: application/json
